# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('python', '编程技术'), ('sql', '数据库'), ('java', '编程')], default=('python', '编程技术'), max_length=200),
        ),
    ]
